receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    verbosity: detailed

extensions:
  pprof:
  zpages:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
