version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    day: sunday
    interval: weekly
- package-ecosystem: gomod
  directory: /
  schedule:
    day: sunday
    interval: weekly
- package-ecosystem: gomod
  directory: /example
  schedule:
    day: sunday
    interval: weekly
